exclude: |
    (?x)^(
      imgs/|
      docs/|
      ci_check/|
      requirements/|
      scripts/
    )
repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: ["--max-line-length=100", "--ignore=F403,F401,W503,W504,E402"]
        exclude: configs/
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        exclude: configs/
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args: ["--style={column_limit: 100}"]
        exclude: configs/
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: |
            (?x)^(
                .*\.jsonl|
                .*\.md.template|
                configs/
            )
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: |
            (?x)^(
              configs/.*?/.*\.txt
            )
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
              configs/.*?/.*\.txt
            )
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        args: ["--number", "--table-width", "200"]
        additional_dependencies:
          - mdformat-openmmlab
          - mdformat_frontmatter
          - linkify-it-py
        exclude: configs/
  - repo: https://github.com/myint/docformatter
    rev: v1.7.6
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-descriptions", "100"]
