base:
    seed: &seed 42
model:
    type: WanI2V
    path: /path/to/model
    lora_path: /path/to/lora_weights
    torch_dtype: auto
calib:
    name: i2v
    download: False
    path: ../assets/wan_i2v/calib/
    sample_steps: 40
    bs: 1
    target_height: 480
    target_width: 832
    num_frames: 81
    guidance_scale: 5.0
    seed: *seed
eval:
    eval_pos: [fake_quant]
    type: video_gen
    name: i2v
    download: False
    path: ../assets/wan_i2v/eval/
    bs: 1
    target_height: 480
    target_width: 832
    num_frames: 81
    guidance_scale: 5.0
    output_video_path: ./output_videos_sq/
quant:
    video_gen:
        method: SmoothQuant
        weight:
            bit: 8
            symmetric: True
            granularity: per_channel
        act:
            bit: 8
            symmetric: True
            granularity: per_token
        special:
            alpha: 0.75
save:
    save_lightx2v: True
    save_path: /path/to/x2v/
